SELECT 
B.AP_ID, B.MAIN_ITEM_ID, B.ORDER_ACTION_ID, B.STATE, B.SERVICE_TYPE, B.START_DATE, B.END_DATE, B.ESNMEID, B.LOGSTS_ACA,
B.COMMST, B.COMMED, B.STATUS_CMTM, B.NOINST, B.CMPRD, B.COMMST_RNK AS CMTM_COMMST_RNK, B.JOB_STAT_DATE FROM
(
SELECT
ROW_NUMBER() OVER(PARTITION BY A.MASTER_SUBSCRIBER_ID ORDER BY CASE WHEN A.STATUS_CMTM='AC' THEN 1 ELSE 2 END, 
CASE WHEN A.STATUS_CMTM='SU' THEN 1 ELSE 3 END,                                                     
A.COMMST_RNK DESC, A.START_DATE DESC) AS RN,
A.AP_ID, 
A.MAIN_ITEM_ID, 
A.ORDER_ACTION_ID, 
A.STATE, 
A.SERVICE_TYPE, 
A.START_DATE, 
A.END_DATE, 
A.ESNMEID, 
A.LOGSTS_ACA,
A.COMMST, 
A.COMMED, 
A.STATUS_CMTM, 
A.NOINST, 
A.CMPRD,
A.COMMST_RNK,
A.JOB_STAT_DATE
FROM (
SELECT
/* PARALLEL(TBAP_ITEM_NOLOB_MV,16)*/ 
A.AP_ID, A.MAIN_ITEM_ID, A.ORDER_ACTION_ID, A.STATE, A.SERVICE_TYPE, A.START_DATE, A.END_DATE, A.ESNMEID, A.LOGSTS_ACA, B.MASTER_SUBSCRIBER_ID,
TO_CHAR(TO_DATE(A.COMMST,'DD/MM/YYYY HH24:MI:SS'),'MM/DD/YYYY') AS COMMST,
TO_CHAR(TO_DATE(A.COMMED,'DD/MM/YYYY HH24:MI:SS'),'MM/DD/YYYY') AS COMMED,
CASE WHEN VALIDATE_CONVERSION(A.COMMST AS DATE,'DD/MM/YYYY HH24:MI:SS')=1 
THEN TO_DATE(A.COMMST,'DD/MM/YYYY HH24:MI:SS') ELSE NULL END AS COMMST_RNK,
CASE WHEN A.STATUS ='CE' THEN 'CE' 
     WHEN SYSDATE > (CASE WHEN VALIDATE_CONVERSION(A.COMMED AS DATE,'DD/MM/YYYY HH24:MI:SS')=1 THEN TO_DATE(A.COMMED,'DD/MM/YYYY HH24:MI:SS') ELSE NULL END) THEN 'CE' ELSE A.STATUS END AS STATUS_CMTM,
A.NOINST, A.CMPRD,
NVL(A.ODS_LAST_UPDATE_DATE, A.ODS_INSERT_DATE) AS JOB_STAT_DATE
FROM OMS_OMS.TBAP_ITEM_NOLOB_MV A
INNER JOIN APP_STAGE.STG_PRE_HRLY_MSTR_SSCR_DELTA_HST B ON TRIM(A.MAIN_ITEM_ID) = TRIM(B.MASTER_SUBSCRIBER_ID)
WHERE A.STATE = 'AS'
AND A.SERVICE_TYPE IN ('CMTM')
AND A.END_DATE BETWEEN '01-JAN-2038' AND '31-DEC-2038'
)A
)B
WHERE B.RN=1